# Generated by Django 3.2.8 on 2021-10-11 14:52

import apps.images.models
import apps.images.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Original image file uploaded by the user.', upload_to=apps.images.models.image_directory_path, validators=[apps.images.validators.validate_content_type])),
                ('alt', models.CharField(blank=True, help_text='Image description that can be used in HTML `alt` attribute.', max_length=250, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID field used mainly for url lookups of the image.')),
                ('account', models.ForeignKey(help_text='User account of the owner of the image.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
