# Generated by Django 3.2.8 on 2021-10-11 07:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models


def create_basic_plans(apps, schema_editor):
    """
    Creates 3 basic plans: `Basic`, `Premium`, `Enterprise`.
    `Basic` plan is created under id = 1 which is the default plan for users.
    """
    Plan = apps.get_model("plans", "Plan")
    basic = Plan(name="Basic", available_thumbnail_heights=[200], can_access_original_image=False, can_fetch_expiring_link=False)
    basic.save()
    premium = Plan(name="Premium", available_thumbnail_heights=[200,400], can_access_original_image=True, can_fetch_expiring_link=False)
    premium.save()
    enterprise = Plan(name="Enterprise", available_thumbnail_heights=[200,400], can_access_original_image=True, can_fetch_expiring_link=True, expiring_link_time_range=(300, 30000))
    enterprise.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the account tier.', max_length=50)),
                ('available_thumbnail_heights', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, help_text='This is a list of available thumbnail heights in pixels (px).', null=True, size=None)),
                ('can_access_original_image', models.BooleanField(help_text='Ability to access original image.')),
                ('can_fetch_expiring_link', models.BooleanField(help_text='Ability to fetch a link that expires after a number of seconds.')),
                ('expiring_link_time_range', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, help_text='Minimum and maximum number of seconds for the expiring link to expire. To be specified by user.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),

        migrations.RunPython(create_basic_plans),
    ]
